#!/bin/bash

function echov {
    if $VERBOSE; then
        echo "$1"
    fi
}

function evalv {
    if $VERBOSE; then
        eval "$1"
    else 
        eval "$1 &> /dev/null"
    fi
}

if $ANSIBLE_SSH; then
    echov "# Starting SSH deamon..."
    evalv "/usr/sbin/sshd"
fi

echov "### Installing ansible-$ANSIBLE_VERSION ..."
GIT="git checkout -b $ANSIBLE_VERSION"
echov "# $GIT"
evalv "$GIT"

if [ ! -f "$ANSIBLE_CONFIG" ]; then
    echov "# copy example config..."
    CPCONF="cp examples/ansible.cfg $ANSIBLE_CONFIG"
    echov "# $CPCONF"
    evalv "$CPCONF" 
fi

echov "# build environment: "
evalv "source ./hacking/env-setup"

echov "have fun!"

exec $@
